require "forwardable"

require "latinverb_infinitives/version"
require "latinverb_infinitives/infinitives_factory"
require "latinverb_infinitives/infinitives_factory/infinitivizer"
require "latinverb_infinitives/infinitives_factory/deponent_infinitivizer"
require "latinverb_infinitives/infinitives_factory/passive_infinitive_factory"
